export const RECEIVE_STATE_UPDATE = 'RECEIVE_STATE_UPDATE';
export const ON_CONNECT_CLOSE = 'ON_CONNECT_CLOSE';
export const CONNECT_READY = 'CONNECT_READY';
export const SESSION_TIMEOUT = 'SESSION_TIMEOUT';
